title: Eris' Notes
author: Eris Tubo
email: eristubi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  THIS PORTFOLIO IS DEPRICATED, please visit my new entry page on upachin.github.io ♥
# Handcrafted Pixels / Memes & Schemes / Codes Smithing / Sexy Management / Eulogy Of 2018 / Morning Coffees / Love for List
version: V-0.1.12
# Google Analytics
google_analytics_id: UN-XXXX

# Social sites
social_sites:
  twitter: eristubo
  github:  eristubo
  #dribbble: eristubo
  #facebook: eristubo
  #flickr: eristubo
  #instagram: eristubo
  #linkedin: eristubo
  #pinterest: eristubo
  #youtube: eristub
  #googleplus: +eristubo
  rss: rss

# Exordium date format
exordium:
  date_format: "%b %-d, %Y"

# Build settings

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemlfile.lock
