title: Handcrafting fine digital goods
author: Eris Tubo
email: eristubi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HI! I'm Eris and I create lots of goodies with a faint touch of danks and memes.
  This blog is like a collection of the sweets that I left all over the internet :relaxed:

# Google Analytics
google_analytics_id: UN-XXXX

# Social sites
social_sites:
  twitter: eristubo
  github:  eristubo
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  instagram: eristubo
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll
  rss: rss

# Exordium date format
exordium:
  date_format: "%b %-d, %Y"

# Build settings

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemlfile.lock
