title: Eris' Notes
author: Eris Tubo
email: eristubi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Handcrafted Pixels / Danks and Memes / Aestetic codes / Eulogy Of 2018 / Morning coffee / Love for List
version: V-0.1.12
# Google Analytics
google_analytics_id: UN-XXXX

# Social sites
social_sites:
  twitter: eristubo
  github:  eristubo
  #dribbble: eristubo
  #facebook: eristubo
  #flickr: eristubo
  #instagram: eristubo
  #linkedin: eristubo
  #pinterest: eristubo
  #youtube: eristub
  #googleplus: +eristubo
  rss: rss

# Exordium date format
exordium:
  date_format: "%b %-d, %Y"

# Build settings

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemlfile.lock
