title: Your awesome title
author: Eris Tubo
email: eristubi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Google Analytics
google_analytics_id: UN-XXXX

# Social sites
social_sites:
  twitter: jekyllrb
  github:  jekyll
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  #instagram: jekyll
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll
  rss: rss

# Exordium date format
exordium:
  date_format: "%b %-d, %Y"

# Build settings

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemlfile.lock
