title: Eris' Notes
author: Eris Tubo
email: eristubi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Handrafted pixels / Coding aesthetic  / Eulogy of 2018 / Morning coffee kisses

# Google Analytics
google_analytics_id: UN-XXXX

# Social sites
social_sites:
  twitter: eristubo
  github:  eristubo
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  instagram: eristubo
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll
  rss: rss

# Exordium date format
exordium:
  date_format: "%b %-d, %Y"

# Build settings

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemlfile.lock
